scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: node-exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - docker-host:9100
    #- node-exporter:9100

remote_write:
  - url: http://mimir:8080/api/v1/push
    headers:
      X-Scope-OrgID: vtj
