scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
    - node-exporter:9100

remote_write:
  - url: http://mimir:8080/api/v1/push
    headers:
      X-Scope-OrgID: vtj
