name: Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    permissions:
      pages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: yarn install --no-progress --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - name: Deploy to https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
